<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWpf>true</UseWpf>
    <RootNamespace>OOP_Practice_9</RootNamespace>
    <AssemblyName>OOP_Practice_9</AssemblyName>
    <LangVersion>7.3</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Images\koff.png" />
    <None Remove="Images\kon.png" />
    <None Remove="Images\loff.png" />
    <None Remove="Images\lon.png" />
    <None Remove="Images\p1.jpg" />
    <None Remove="Images\roff.png" />
    <None Remove="Images\ron.png" />
    <None Remove="Images\rp1.jpg" />
    <None Remove="Images\soff.png" />
    <None Remove="Images\son.png" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes" Version="4.9.0" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Images\koff.png" />
    <Resource Include="Images\kon.png" />
    <Resource Include="Images\loff.png" />
    <Resource Include="Images\lon.png" />
    <Resource Include="Images\p1.jpg" />
    <Resource Include="Images\roff.png" />
    <Resource Include="Images\ron.png" />
    <Resource Include="Images\rp1.jpg" />
    <Resource Include="Images\soff.png" />
    <Resource Include="Images\son.png" />
  </ItemGroup>
</Project>
